spring:
  application:
    name: trip-service
  # MongoDB 추가

  data:
    mongodb:
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8081

springdoc:
  api-docs:
    path: /api/trip/v3/api-docs
  swagger-ui:
    path: /api/trip/swagger-ui.html

cloud:
  aws:
    credentials:
      access-key: ${AWS_S3_ACCESSKEY}
      secret-key: ${AWS_S3_SECRETKEY}
    s3:
      bucket: ${AWS_S3_BUCKETNAME}