spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    properties:
      hibernate:
        show_sql: true #만들어진 sql 보여줌
        format_sql: true #sql 가독성 좋게 보여줌
    hibernate:
      ddl-auto: create #db 초기화 전략. 기존 테이블 삭제 후 생성
    database-platform: org.hibernate.dialect.MySQLDialect
  security: # OAuth2
    oauth2:
      client:
        registration:
          naver:
            client-id: _cFgoA5jCXN10jJ6pAoo
            client-secret: 74r0jJN6uX
            scope: name, email, profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            redirect-uri: https://i10a701.p.ssafy.io/api/user/login/oauth2/code/naver

          kakao:
            client-id: 27a9fd30b37529913566120655684173
            client-secret: EWHyUTLk1Gr7vkNsVgbvO1AAMtsjTBp5
            client-name: kakao-login
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            redirect-uri: https://i10a701.p.ssafy.io/api/user/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
server:
  port: 8081

grpc:
  server:
    port: 9090

springdoc:
  api-docs:
    path: /api/user/v3/api-docs
  swagger-ui:
    path: /api/user/swagger-ui.html
