spring:
  application:
    name: message-service
  #database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
<<<<<<< Updated upstream
#    url: jdbc:mysql://mysql-container:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    url: jdbc:mysql://i10a701.p.ssafy.io:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    url: jdbc:mysql://localhost:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
=======
    url: jdbc:mysql://i10a701.p.ssafy.io:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
>>>>>>> Stashed changes
    username: root
    password: ssafy
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        fomat_sql: true
    hibernate:
      ddl-auto: update
      hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy


  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

server:
  port: 8084

springdoc:
  api-docs:
    path: /api/message/v3/api-docs
  swagger-ui:
    path: /api/message/swagger-ui.html


# grpc를 위해 추가
grpc:
  client:
    user-service:
#      address: 'static://127.0.0.1:9091'
      address: 'static://user-service:9090'
<<<<<<< Updated upstream
      negotiationtype: plaintext
=======
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://eureka-server:8761/
>>>>>>> Stashed changes
