spring:
  application:
    name: message-service
  #database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/narangdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: ssafy
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        fomat_sql: true
    hibernate:
      ddl-auto: update
      hibernate:
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
#        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    addresses: rabbitmq
    
server:
  port: 8084

springdoc:
  api-docs:
    path: /api/message/v3/api-docs
  swagger-ui:
    path: /api/message/swagger-ui.html

# grpc를 위해 추가
grpc:
  client:
#      address: 'static://user-service:9090'
#      negotiationtype: plaintext
    user-service:
      address: 'static://user-service:9090'

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/